---
title: "EylulIsilAltiparmak-Muy665-Odev1-Soru4"
---

# MUY665 Is Analigi 2025-2026 Bahar Donemi Odev-1  Soru-4 / Eylul Isil Altiparmak

## dslabs paketinden polls_us_election_2016 veri setini ice aktarin.

library(dslabs) data("polls_us_election_2016") data\<-polls_us_election_2016

## Dokumaninizin en ustunde asagidaki iki degiskeni tanimlayin (kendi bilgilerinizi kullanin):

my_first\<-"EylulIsil" my_birth_year\<-1997

## Bir k tamsayisini (integer) asagidaki gibi tanimlayin:

k\<-(nchar(my_first)+my_birth_year)%%15+8

## Asagidaki kurali kullanarak orijinal veri setinin k adet satirini web sayfanizda goruntuleyin:

if(k%%2==0){ head(data,k) }else{ tail(data,k) }

# Hesaplayin ve goruntuleyin:

## – Tum veri setindeki toplam NA (eksik) değer sayisi

sum(is.na(data)) \## – En buyukten en kucuge siralanmis sekilde sutun basina NA deger sayisi (ilk 8 sutunu goruntuleyin) na_count\<-sapply(data\[1:8\],function(x)sum(is.na(x))) sort(na_count,decreasing=TRUE)

# Veri setindeki tum NA degerlerini asagidaki gibi degistirin ve sonucu yeni bir nesne olarak kaydedin (orijinalin uzerine yazmayin):

new_data\<-data

## Sayisal (numeric) sutunlar icin: NA degerlerini my_birth_year + k ile degistirin.

## Karakter (character) veya faktor (factor) sutunları icin: NA degerlerini paste0(my_first, "\_", k) ile degistirin.

new_data \<- data\
for(i in 1:length(new_data\[1,\])){\
if(is.numeric(new_data\[\[i\]\])){ new_data\[\[i\]\]\[is.na(new_data\[\[i\]\])\] \<- my_birth_year + k } else { new_data\[\[i\]\] \<- as.character(new_data\[\[i\]\]) new_data\[\[i\]\]\[is.na(new_data\[\[i\]\])\] \<- paste0(my_first, "\_", k) } }

# Yeni veri cercevesi (data frame) icin cıktıları yazdirin:

## Yukaridakiyle tamamen ayni kurali kullanarak yeni veri cercevesinin k satirini goruntuleyin:

## – Eger k cift ise, yeni veri cercevesinin ilk k satirini gosterin.

## – Eger k tek ise, yeni veri cercevesinin son k satirini gosterin.

if(k %% 2 == 0){\
head(new_data, k) } else {\
tail(new_data, k) }

## Yeni veri cercevesinde kalan toplam NA deger sayisini goruntuleyin.

sum(is.na(new_data))

## Ayrica anyNA(new_data) komutunu da yazdirin (Eger dogru bir sekilde degistirdiyseniz FALSE dondurmelidir).

anyNA(new_data)
